// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://funszpqfpupiuacmovui.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ1bnN6cHFmcHVwaXVhY21vdnVpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyMzQ3ODEsImV4cCI6MjA2NzgxMDc4MX0.kHORngxiPzcVYe3-ui6vBf6eT-uyl8JU8CE1bCXdFQM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});